services:
  floci:
    image: floci/floci:latest

    environment:
      FLOCI_HOSTNAME: floci
      FLOCI_SERVICES_ECR_URI_STYLE: path
      FLOCI_RUN_AS_ROOT: "true"

    ports:
      - "4566:4566"

    volumes:
      - floci-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
  worker:
    profiles:
      - worker

    build:
      context: .
      dockerfile: Dockerfile.worker

    environment:
      AWS_ENDPOINT_URL: http://floci:4566
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test

      KINESIS_STREAM_NAME: commerce-stream-events
      METRICS_TABLE_NAME: event-ingestion-metrics
      PROCESSED_EVENTS_TABLE_NAME: event-ingestion-processed-events

    depends_on:
      - floci
volumes:
  floci-data:
